// SuperABC - Dados Iniciais da Transição Contábil 2026
const SUPERABC_DATA = {
    projeto: {
        nome: "Transição Contábil Grupo Super ABC",
        cliente: "Grupo Super ABC",
        consultoria: "A2Consultores",
        periodo: "Abril/2026 - Junho/2026",
        duracao: "12 semanas",
        data_inicio: "2026-04-01",
        total_tarefas: 32,
        total_empresas: 6
    },
    tarefas: [
        { id: "1.1", tarefa: "Certificado digital para acessar o eSocial (A1)", responsavel: "Yuri Silva", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Folha de Pagamento", observacoes: "" },
        { id: "1.2", tarefa: "Folhas de pagamentos de Jan até a Atual", responsavel: "DP", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Folha de Pagamento", observacoes: "" },
        { id: "1.3", tarefa: "Código de acesso e senha do seguro-desemprego", responsavel: "DP", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Folha de Pagamento", observacoes: "" },
        { id: "1.4", tarefa: "Convenção coletiva completa 2025/2026", responsavel: "DP", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Folha de Pagamento", observacoes: "" },
        { id: "1.5", tarefa: "Relatórios de afastamentos 2025 e 2026", responsavel: "DP", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Folha de Pagamento", observacoes: "" },
        { id: "1.6", tarefa: "Relatório de pensão alimentícia se houver 2025/2026", responsavel: "DP", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Folha de Pagamento", observacoes: "" },
        { id: "1.7", tarefa: "Relatórios de Dependentes", responsavel: "DP", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Folha de Pagamento", observacoes: "" },
        { id: "1.8", tarefa: "Média de horas extras para emissão de férias 2025/2026", responsavel: "DP", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Folha de Pagamento", observacoes: "" },
        { id: "1.9", tarefa: "Relatório de desconto de convênio com prestadora 2026", responsavel: "DP", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Folha de Pagamento", observacoes: "" },
        { id: "1.10", tarefa: "Relatório de descontos fixos em folha 2026", responsavel: "DP", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Folha de Pagamento", observacoes: "" },
        { id: "1.11", tarefa: "Relatório de faltas dos períodos 2025 e 2026", responsavel: "DP", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Folha de Pagamento", observacoes: "" },
        { id: "1.12", tarefa: "Atualizações CTPS e fichas de registro completa", responsavel: "DP", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Folha de Pagamento", observacoes: "" },
        { id: "1.13", tarefa: "Fichas financeiras de 2025 e 2026", responsavel: "DP", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Folha de Pagamento", observacoes: "" },
        { id: "1.14", tarefa: "Relatório de férias - último", responsavel: "DP", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Folha de Pagamento", observacoes: "" },
        { id: "2.1", tarefa: "Plano de contas das empresas - Contábil e financeiro", responsavel: "Tatiane Ferreira", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Informações Contábeis", observacoes: "" },
        { id: "2.2", tarefa: "Composição de saldos do último mês", responsavel: "Contábil", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Informações Contábeis", observacoes: "" },
        { id: "2.3", tarefa: "Controle do ativo imobilizado", responsavel: "Contábil", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Informações Contábeis", observacoes: "" },
        { id: "2.4", tarefa: "Balancete de dezembro de 2025 até atual", responsavel: "Contábil", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Informações Contábeis", observacoes: "" },
        { id: "2.5", tarefa: "Balancetes mensais de janeiro a dezembro de 2025 até o atual", responsavel: "Contábil", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Informações Contábeis", observacoes: "" },
        { id: "2.6", tarefa: "SPED Contábil (ECD) - com certificado digital", responsavel: "Contábil", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Informações Contábeis", observacoes: "" },
        { id: "2.7", tarefa: "Fechamento Contábil do último mês", responsavel: "Contábil", inicio: "01/04/2026", fim: "10/04/2026", dias: 10, percentual: 0, status: "PENDENTE", departamento: "Informações Contábeis", observacoes: "" },
        { id: "3.1", tarefa: "Certificado digital A1 (para buscar notas fiscais)", responsavel: "Everton Menezes", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Informações Fiscais", observacoes: "" },
        { id: "3.2", tarefa: "Contrato Social última alteração", responsavel: "Fiscal", inicio: "01/04/2026", fim: "10/04/2026", dias: 10, percentual: 0, status: "PENDENTE", departamento: "Informações Fiscais", observacoes: "" },
        { id: "3.3", tarefa: "Procuração eletrônica para nosso CNPJ 14.784.072/0001-81", responsavel: "Fiscal", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Informações Fiscais", observacoes: "" },
        { id: "3.4", tarefa: "Procuração eletrônica Prefeitura de São Paulo", responsavel: "Fiscal", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Informações Fiscais", observacoes: "" },
        { id: "3.5", tarefa: "Cálculos do PIS e da COFINS 2025 até atual", responsavel: "Fiscal", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Informações Fiscais", observacoes: "" },
        { id: "3.6", tarefa: "Cálculos do IRPJ e da CSLL de 2025 até atual", responsavel: "Fiscal", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Informações Fiscais", observacoes: "" },
        { id: "3.7", tarefa: "Cálculos do ICMS 2025 até atual", responsavel: "Fiscal", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Informações Fiscais", observacoes: "" },
        { id: "3.8", tarefa: "Cálculos do ISS 2025 até atual", responsavel: "Fiscal", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Informações Fiscais", observacoes: "" },
        { id: "3.9", tarefa: "Senha do posto fiscal (Fazenda Estadual SP)", responsavel: "Fiscal", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Informações Fiscais", observacoes: "" },
        { id: "3.10", tarefa: "Senha da prefeitura do Município", responsavel: "Fiscal", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Informações Fiscais", observacoes: "" },
        { id: "3.11", tarefa: "Controle de parcelamentos débitos fiscais (se houver)", responsavel: "Fiscal", inicio: "01/04/2026", fim: "09/04/2026", dias: 9, percentual: 0, status: "PENDENTE", departamento: "Informações Fiscais", observacoes: "" }
    ],
    checklist: [
        { id: 1, categoria: "FOLHA DE PAGAMENTO", documento: "Certificado digital eSocial (A1)", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 2, categoria: "FOLHA DE PAGAMENTO", documento: "Folhas de pagamento Jan/2026 até atual", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 3, categoria: "FOLHA DE PAGAMENTO", documento: "Código de acesso seguro-desemprego", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 4, categoria: "FOLHA DE PAGAMENTO", documento: "Convenção coletiva 2025/2026", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 5, categoria: "FOLHA DE PAGAMENTO", documento: "Relatórios de afastamentos 2025/2026", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 6, categoria: "FOLHA DE PAGAMENTO", documento: "Relatório pensão alimentícia 2025/2026", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 7, categoria: "FOLHA DE PAGAMENTO", documento: "Relatório de dependentes", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 8, categoria: "FOLHA DE PAGAMENTO", documento: "Média de horas extras 2025/2026", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 9, categoria: "FOLHA DE PAGAMENTO", documento: "Relatório desconto convênio 2026", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 10, categoria: "FOLHA DE PAGAMENTO", documento: "Relatório descontos fixos folha 2026", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 11, categoria: "FOLHA DE PAGAMENTO", documento: "Relatório de faltas 2025/2026", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 12, categoria: "FOLHA DE PAGAMENTO", documento: "CTPS e fichas de registro atualizadas", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 13, categoria: "FOLHA DE PAGAMENTO", documento: "Fichas financeiras 2025/2026", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 14, categoria: "FOLHA DE PAGAMENTO", documento: "Relatório de férias - último", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 15, categoria: "CONTÁBIL", documento: "Plano de contas contábil e financeiro", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 16, categoria: "CONTÁBIL", documento: "Composição de saldos último mês", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 17, categoria: "CONTÁBIL", documento: "Controle do ativo imobilizado", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 18, categoria: "CONTÁBIL", documento: "Balancete dezembro/2025 até atual", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 19, categoria: "CONTÁBIL", documento: "Balancetes mensais jan/2025 até atual", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 20, categoria: "CONTÁBIL", documento: "SPED Contábil (ECD)", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 21, categoria: "CONTÁBIL", documento: "Fechamento contábil último mês", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 22, categoria: "FISCAL", documento: "Certificado digital A1", empresa: "Todas", entregue: true, data_entrega: "", responsavel: "Cliente" },
        { id: 23, categoria: "FISCAL", documento: "Contrato Social última alteração", empresa: "Todas", entregue: true, data_entrega: "", responsavel: "Cliente" },
        { id: 24, categoria: "FISCAL", documento: "Procuração eletrônica RFB", empresa: "Todas", entregue: true, data_entrega: "", responsavel: "Cliente" },
        { id: 25, categoria: "FISCAL", documento: "Procuração eletrônica Prefeitura SP", empresa: "Todas", entregue: true, data_entrega: "", responsavel: "Cliente" },
        { id: 26, categoria: "FISCAL", documento: "Cálculos PIS/COFINS 2025/atual", empresa: "Todas", entregue: true, data_entrega: "", responsavel: "Cliente" },
        { id: 27, categoria: "FISCAL", documento: "Cálculos IRPJ/CSLL 2025/atual", empresa: "Todas", entregue: true, data_entrega: "", responsavel: "Cliente" },
        { id: 28, categoria: "FISCAL", documento: "Cálculos ICMS 2025/atual", empresa: "Todas", entregue: true, data_entrega: "", responsavel: "Cliente" },
        { id: 29, categoria: "FISCAL", documento: "Cálculos ISS 2025/atual", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 30, categoria: "FISCAL", documento: "Senha posto fiscal Fazenda Estadual SP", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 31, categoria: "FISCAL", documento: "Senha prefeitura Município", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" },
        { id: 32, categoria: "FISCAL", documento: "Controle parcelamentos débitos fiscais", empresa: "Todas", entregue: false, data_entrega: "", responsavel: "Cliente" }
    ],
    empresas: [
        { id: 1, nome: "SUPER ABC COMERCIO DE FERRAGENS E FERRAMENTAS LTDA", cnpj: "06.351.146/0001-68", estado: "SP", funcionarios: 4, status: "Ativa" },
        { id: 2, nome: "MUNDO EXPRESS COMERCIO E DEPOSITO DE MERCADORIAS LTDA", cnpj: "62.446.439/0001-08", estado: "SP", funcionarios: 75, status: "Ativa" },
        { id: 3, nome: "BEM COMERCIO E SERVICOS ADMINISTRATIVOS LTDA", cnpj: "62.521.587/0001-31", estado: "SP", funcionarios: 26, status: "Ativa" },
        { id: 4, nome: "CONSTRUIR BEM COMERCIO DE MATERIAIS PARA CONSTRUCAO LTDA", cnpj: "63.354.477/0001-95", estado: "SP", funcionarios: 4, status: "Ativa" },
        { id: 5, nome: "EROS ADMINISTRACAO DE BENS LTDA", cnpj: "60.663.045/0001-78", estado: "SP", funcionarios: 0, status: "Ativa" },
        { id: 6, nome: "LIQUIDALAR COMERCIO DE MATERIAIS PARA CONSTRUCAO LTDA", cnpj: "14.292.807/0001-50", estado: "SP", funcionarios: 4, status: "Ativa" }
    ],
    equipe: [
        { departamento: "DIRETORIA", nome: "André Alves Coelho", email: "andre@a2consultores.com.br", telefone: "(11) 96482-2296" },
        { departamento: "DEPTO. CONTÁBIL", nome: "Tatiane Ferreira", email: "tatiane.ferreira@a2consultores.com.br", telefone: "(11) 96482-2296" },
        { departamento: "DEPTO. FISCAL", nome: "Everton Menezes", email: "everton@a2consultores.com.br", telefone: "(11) 96482-2296" },
        { departamento: "DEPTO. PESSOAL", nome: "Yuri Silva", email: "dp01@a2consultores.com.br", telefone: "(11) 96482-2296" },
        { departamento: "PARALEGAL", nome: "William Kodama", email: "william.kodama@a2consultores.com.br", telefone: "(11) 96482-2296" },
        { departamento: "FINANCEIRO", nome: "José Mateus", email: "financeiro@a2consultores.com.br", telefone: "(11) 96482-2296" }
    ],
    prazos: [
        { tipo: "CRÍTICO", prazo: "24h antes", descricao: "Admissão de funcionários", responsavel: "DEPTO. PESSOAL" },
        { tipo: "FIXO", prazo: "5º dia útil", descricao: "Fechamento mensal contábil", responsavel: "DEPTO. CONTÁBIL" },
        { tipo: "FIXO", prazo: "5º dia útil", descricao: "Notas fiscais de serviços", responsavel: "DEPTO. FISCAL" },
        { tipo: "URGENTE", prazo: "Imediato", descricao: "Rescisões e afastamentos", responsavel: "DEPTO. PESSOAL" },
        { tipo: "FIXO", prazo: "5 dias antes", descricao: "Apontamentos de folha", responsavel: "DEPTO. PESSOAL" }
    ],
    links: [
        { sistema: "eSocial", descricao: "Folha de pagamento e trabalhista", url: "https://portal.esocial.gov.br", acesso: "Certificado A1" },
        { sistema: "SPED", descricao: "Escrituração fiscal digital", url: "https://www.sped.fazenda.gov.br", acesso: "Certificado A1" },
        { sistema: "RFB", descricao: "Receita Federal", url: "https://www.gov.br/receitafederal", acesso: "Certificado ou senha" },
        { sistema: "Sefaz SP", descricao: "Fazenda Estadual SP", url: "https://www.fazenda.sp.gov.br", acesso: "Senha ou certificado" },
        { sistema: "Prefeitura SP", descricao: "Notas fiscais de serviços", url: "https://nfe.prefeitura.sp.gov.br", acesso: "Certificado A1" },
        { sistema: "Simples Nacional", descricao: "Portal do Simples", url: "https://www8.receita.fazenda.gov.br", acesso: "Certificado A1" }
    ]
};
